/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.Company;
import org.openapitools.client.model.SchoolTutor;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Student
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-03-03T11:04:11.316594500+01:00[Europe/Madrid]", comments = "Generator version: 7.12.0")
public class Student {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nullable
  private Long id;

  public static final String SERIALIZED_NAME_FULL_NAME = "fullName";
  @SerializedName(SERIALIZED_NAME_FULL_NAME)
  @javax.annotation.Nullable
  private String fullName;

  public static final String SERIALIZED_NAME_COURSE = "course";
  @SerializedName(SERIALIZED_NAME_COURSE)
  @javax.annotation.Nullable
  private String course;

  public static final String SERIALIZED_NAME_INTERNSHIP_PERIOD = "internshipPeriod";
  @SerializedName(SERIALIZED_NAME_INTERNSHIP_PERIOD)
  @javax.annotation.Nullable
  private String internshipPeriod;

  public static final String SERIALIZED_NAME_COURSE_YEAR = "courseYear";
  @SerializedName(SERIALIZED_NAME_COURSE_YEAR)
  @javax.annotation.Nullable
  private String courseYear;

  public static final String SERIALIZED_NAME_SCHOOL_TUTOR = "schoolTutor";
  @SerializedName(SERIALIZED_NAME_SCHOOL_TUTOR)
  @javax.annotation.Nullable
  private SchoolTutor schoolTutor;

  public static final String SERIALIZED_NAME_ASSIGNED_COMPANY = "assignedCompany";
  @SerializedName(SERIALIZED_NAME_ASSIGNED_COMPANY)
  @javax.annotation.Nullable
  private Company assignedCompany;

  public Student() {
  }

  public Student id(@javax.annotation.Nullable Long id) {
    this.id = id;
    return this;
  }

  /**
   * Student ID. Autogenerate on POST requests
   * @return id
   */
  @javax.annotation.Nullable
  public Long getId() {
    return id;
  }

  public void setId(@javax.annotation.Nullable Long id) {
    this.id = id;
  }


  public Student fullName(@javax.annotation.Nullable String fullName) {
    this.fullName = fullName;
    return this;
  }

  /**
   * Get fullName
   * @return fullName
   */
  @javax.annotation.Nullable
  public String getFullName() {
    return fullName;
  }

  public void setFullName(@javax.annotation.Nullable String fullName) {
    this.fullName = fullName;
  }


  public Student course(@javax.annotation.Nullable String course) {
    this.course = course;
    return this;
  }

  /**
   * Get course
   * @return course
   */
  @javax.annotation.Nullable
  public String getCourse() {
    return course;
  }

  public void setCourse(@javax.annotation.Nullable String course) {
    this.course = course;
  }


  public Student internshipPeriod(@javax.annotation.Nullable String internshipPeriod) {
    this.internshipPeriod = internshipPeriod;
    return this;
  }

  /**
   * Get internshipPeriod
   * @return internshipPeriod
   */
  @javax.annotation.Nullable
  public String getInternshipPeriod() {
    return internshipPeriod;
  }

  public void setInternshipPeriod(@javax.annotation.Nullable String internshipPeriod) {
    this.internshipPeriod = internshipPeriod;
  }


  public Student courseYear(@javax.annotation.Nullable String courseYear) {
    this.courseYear = courseYear;
    return this;
  }

  /**
   * Get courseYear
   * @return courseYear
   */
  @javax.annotation.Nullable
  public String getCourseYear() {
    return courseYear;
  }

  public void setCourseYear(@javax.annotation.Nullable String courseYear) {
    this.courseYear = courseYear;
  }


  public Student schoolTutor(@javax.annotation.Nullable SchoolTutor schoolTutor) {
    this.schoolTutor = schoolTutor;
    return this;
  }

  /**
   * Get schoolTutor
   * @return schoolTutor
   */
  @javax.annotation.Nullable
  public SchoolTutor getSchoolTutor() {
    return schoolTutor;
  }

  public void setSchoolTutor(@javax.annotation.Nullable SchoolTutor schoolTutor) {
    this.schoolTutor = schoolTutor;
  }


  public Student assignedCompany(@javax.annotation.Nullable Company assignedCompany) {
    this.assignedCompany = assignedCompany;
    return this;
  }

  /**
   * Get assignedCompany
   * @return assignedCompany
   */
  @javax.annotation.Nullable
  public Company getAssignedCompany() {
    return assignedCompany;
  }

  public void setAssignedCompany(@javax.annotation.Nullable Company assignedCompany) {
    this.assignedCompany = assignedCompany;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Student student = (Student) o;
    return Objects.equals(this.id, student.id) &&
        Objects.equals(this.fullName, student.fullName) &&
        Objects.equals(this.course, student.course) &&
        Objects.equals(this.internshipPeriod, student.internshipPeriod) &&
        Objects.equals(this.courseYear, student.courseYear) &&
        Objects.equals(this.schoolTutor, student.schoolTutor) &&
        Objects.equals(this.assignedCompany, student.assignedCompany);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, fullName, course, internshipPeriod, courseYear, schoolTutor, assignedCompany);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Student {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    fullName: ").append(toIndentedString(fullName)).append("\n");
    sb.append("    course: ").append(toIndentedString(course)).append("\n");
    sb.append("    internshipPeriod: ").append(toIndentedString(internshipPeriod)).append("\n");
    sb.append("    courseYear: ").append(toIndentedString(courseYear)).append("\n");
    sb.append("    schoolTutor: ").append(toIndentedString(schoolTutor)).append("\n");
    sb.append("    assignedCompany: ").append(toIndentedString(assignedCompany)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("id");
    openapiFields.add("fullName");
    openapiFields.add("course");
    openapiFields.add("internshipPeriod");
    openapiFields.add("courseYear");
    openapiFields.add("schoolTutor");
    openapiFields.add("assignedCompany");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to Student
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!Student.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in Student is not found in the empty JSON string", Student.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!Student.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `Student` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("fullName") != null && !jsonObj.get("fullName").isJsonNull()) && !jsonObj.get("fullName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `fullName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("fullName").toString()));
      }
      if ((jsonObj.get("course") != null && !jsonObj.get("course").isJsonNull()) && !jsonObj.get("course").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `course` to be a primitive type in the JSON string but got `%s`", jsonObj.get("course").toString()));
      }
      if ((jsonObj.get("internshipPeriod") != null && !jsonObj.get("internshipPeriod").isJsonNull()) && !jsonObj.get("internshipPeriod").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `internshipPeriod` to be a primitive type in the JSON string but got `%s`", jsonObj.get("internshipPeriod").toString()));
      }
      if ((jsonObj.get("courseYear") != null && !jsonObj.get("courseYear").isJsonNull()) && !jsonObj.get("courseYear").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `courseYear` to be a primitive type in the JSON string but got `%s`", jsonObj.get("courseYear").toString()));
      }
      // validate the optional field `schoolTutor`
      if (jsonObj.get("schoolTutor") != null && !jsonObj.get("schoolTutor").isJsonNull()) {
        SchoolTutor.validateJsonElement(jsonObj.get("schoolTutor"));
      }
      // validate the optional field `assignedCompany`
      if (jsonObj.get("assignedCompany") != null && !jsonObj.get("assignedCompany").isJsonNull()) {
        Company.validateJsonElement(jsonObj.get("assignedCompany"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Student.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Student' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Student> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Student.class));

       return (TypeAdapter<T>) new TypeAdapter<Student>() {
           @Override
           public void write(JsonWriter out, Student value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Student read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of Student given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of Student
   * @throws IOException if the JSON string is invalid with respect to Student
   */
  public static Student fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Student.class);
  }

  /**
   * Convert an instance of Student to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

