/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.Dates;
import org.openapitools.client.model.FCTRegister;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for FctRegisterApiServiceApi
 */
@Disabled
public class FctRegisterApiServiceApiTest {

    private final FctRegisterApiServiceApi api = new FctRegisterApiServiceApi();

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createRegisterTest() throws ApiException {
        FCTRegister fcTRegister = null;
        FCTRegister response = api.createRegister(fcTRegister);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteRegisterTest() throws ApiException {
        Long idRegister = null;
        api.deleteRegister(idRegister);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getNotRegisterDatesTest() throws ApiException {
        Long idStudent = null;
        List<Dates> response = api.getNotRegisterDates(idStudent);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getRegisterDatesTest() throws ApiException {
        Long id = null;
        List<FCTRegister> response = api.getRegisterDates(id);
        // TODO: test validations
    }

}
