/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.Company;
import org.openapitools.client.model.SchoolTutor;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Student
 */
public class StudentTest {
    private final Student model = new Student();

    /**
     * Model tests for Student
     */
    @Test
    public void testStudent() {
        // TODO: test Student
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'fullName'
     */
    @Test
    public void fullNameTest() {
        // TODO: test fullName
    }

    /**
     * Test the property 'course'
     */
    @Test
    public void courseTest() {
        // TODO: test course
    }

    /**
     * Test the property 'internshipPeriod'
     */
    @Test
    public void internshipPeriodTest() {
        // TODO: test internshipPeriod
    }

    /**
     * Test the property 'courseYear'
     */
    @Test
    public void courseYearTest() {
        // TODO: test courseYear
    }

    /**
     * Test the property 'schoolTutor'
     */
    @Test
    public void schoolTutorTest() {
        // TODO: test schoolTutor
    }

    /**
     * Test the property 'assignedCompany'
     */
    @Test
    public void assignedCompanyTest() {
        // TODO: test assignedCompany
    }

}
