/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.CreateRegisterRequest;
import org.openapitools.client.model.FCTRegister;
import java.time.LocalDate;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for FctRegisterApiServiceApi
 */
@Disabled
public class FctRegisterApiServiceApiTest {

    private final FctRegisterApiServiceApi api = new FctRegisterApiServiceApi();

    /**
     * Add register
     *
     * Returns added register
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createRegisterTest() throws ApiException {
        CreateRegisterRequest createRegisterRequest = null;
        FCTRegister response = api.createRegister(createRegisterRequest);
        // TODO: test validations
    }

    /**
     * Delete register by ID
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteRegisterTest() throws ApiException {
        Long idRegister = null;
        api.deleteRegister(idRegister);
        // TODO: test validations
    }

    /**
     * Get register by ID
     *
     * Returns a single register
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getRegisterTest() throws ApiException {
        Long idRegister = null;
        FCTRegister response = api.getRegister(idRegister);
        // TODO: test validations
    }

    /**
     * Gets registers of a student by ID
     *
     * Returns a list of registers concurred between specified dates (It may be empty)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getRegisterDatesTest() throws ApiException {
        Long idStudent = null;
        String filtro = null;
        LocalDate since = null;
        LocalDate until = null;
        List<FCTRegister> response = api.getRegisterDates(idStudent, filtro, since, until);
        // TODO: test validations
    }

}
