/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Company
 */
public class CompanyTest {
    private final Company model = new Company();

    /**
     * Model tests for Company
     */
    @Test
    public void testCompany() {
        // TODO: test Company
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'tutorName'
     */
    @Test
    public void tutorNameTest() {
        // TODO: test tutorName
    }

    /**
     * Test the property 'tutorMail'
     */
    @Test
    public void tutorMailTest() {
        // TODO: test tutorMail
    }

    /**
     * Test the property 'tutorTlfno'
     */
    @Test
    public void tutorTlfnoTest() {
        // TODO: test tutorTlfno
    }

    /**
     * Test the property 'active'
     */
    @Test
    public void activeTest() {
        // TODO: test active
    }

}
