/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.Dates;
import org.openapitools.client.model.Student;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for FCTRegister
 */
public class FCTRegisterTest {
    private final FCTRegister model = new FCTRegister();

    /**
     * Model tests for FCTRegister
     */
    @Test
    public void testFCTRegister() {
        // TODO: test FCTRegister
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'associatedStudent'
     */
    @Test
    public void associatedStudentTest() {
        // TODO: test associatedStudent
    }

    /**
     * Test the property 'associatedDate'
     */
    @Test
    public void associatedDateTest() {
        // TODO: test associatedDate
    }

    /**
     * Test the property 'numHours'
     */
    @Test
    public void numHoursTest() {
        // TODO: test numHours
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

}
