/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for StudentDto
 */
public class StudentDtoTest {
    private final StudentDto model = new StudentDto();

    /**
     * Model tests for StudentDto
     */
    @Test
    public void testStudentDto() {
        // TODO: test StudentDto
    }

    /**
     * Test the property 'fullName'
     */
    @Test
    public void fullNameTest() {
        // TODO: test fullName
    }

    /**
     * Test the property 'course'
     */
    @Test
    public void courseTest() {
        // TODO: test course
    }

    /**
     * Test the property 'internshipPeriod'
     */
    @Test
    public void internshipPeriodTest() {
        // TODO: test internshipPeriod
    }

    /**
     * Test the property 'courseYear'
     */
    @Test
    public void courseYearTest() {
        // TODO: test courseYear
    }

    /**
     * Test the property 'tutorName'
     */
    @Test
    public void tutorNameTest() {
        // TODO: test tutorName
    }

    /**
     * Test the property 'companyName'
     */
    @Test
    public void companyNameTest() {
        // TODO: test companyName
    }

    /**
     * Test the property 'hoursTotal'
     */
    @Test
    public void hoursTotalTest() {
        // TODO: test hoursTotal
    }

    /**
     * Test the property 'hoursWorked'
     */
    @Test
    public void hoursWorkedTest() {
        // TODO: test hoursWorked
    }

    /**
     * Test the property 'hoursLeft'
     */
    @Test
    public void hoursLeftTest() {
        // TODO: test hoursLeft
    }

}
