/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.LocalDate;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Dates
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-02-18T19:05:31.746220500+01:00[Europe/Madrid]", comments = "Generator version: 7.11.0")
public class Dates {
  public static final String SERIALIZED_NAME_DATE = "date";
  @SerializedName(SERIALIZED_NAME_DATE)
  @javax.annotation.Nullable
  private LocalDate date;

  public static final String SERIALIZED_NAME_COURSE_YEAR = "courseYear";
  @SerializedName(SERIALIZED_NAME_COURSE_YEAR)
  @javax.annotation.Nullable
  private String courseYear;

  public static final String SERIALIZED_NAME_INTERNSHIP_PERIOD = "internshipPeriod";
  @SerializedName(SERIALIZED_NAME_INTERNSHIP_PERIOD)
  @javax.annotation.Nullable
  private String internshipPeriod;

  public Dates() {
  }

  public Dates date(@javax.annotation.Nullable LocalDate date) {
    this.date = date;
    return this;
  }

  /**
   * Get date
   * @return date
   */
  @javax.annotation.Nullable
  public LocalDate getDate() {
    return date;
  }

  public void setDate(@javax.annotation.Nullable LocalDate date) {
    this.date = date;
  }


  public Dates courseYear(@javax.annotation.Nullable String courseYear) {
    this.courseYear = courseYear;
    return this;
  }

  /**
   * Get courseYear
   * @return courseYear
   */
  @javax.annotation.Nullable
  public String getCourseYear() {
    return courseYear;
  }

  public void setCourseYear(@javax.annotation.Nullable String courseYear) {
    this.courseYear = courseYear;
  }


  public Dates internshipPeriod(@javax.annotation.Nullable String internshipPeriod) {
    this.internshipPeriod = internshipPeriod;
    return this;
  }

  /**
   * Get internshipPeriod
   * @return internshipPeriod
   */
  @javax.annotation.Nullable
  public String getInternshipPeriod() {
    return internshipPeriod;
  }

  public void setInternshipPeriod(@javax.annotation.Nullable String internshipPeriod) {
    this.internshipPeriod = internshipPeriod;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Dates dates = (Dates) o;
    return Objects.equals(this.date, dates.date) &&
        Objects.equals(this.courseYear, dates.courseYear) &&
        Objects.equals(this.internshipPeriod, dates.internshipPeriod);
  }

  @Override
  public int hashCode() {
    return Objects.hash(date, courseYear, internshipPeriod);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Dates {\n");
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    courseYear: ").append(toIndentedString(courseYear)).append("\n");
    sb.append("    internshipPeriod: ").append(toIndentedString(internshipPeriod)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("date");
    openapiFields.add("courseYear");
    openapiFields.add("internshipPeriod");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to Dates
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!Dates.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in Dates is not found in the empty JSON string", Dates.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!Dates.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `Dates` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("courseYear") != null && !jsonObj.get("courseYear").isJsonNull()) && !jsonObj.get("courseYear").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `courseYear` to be a primitive type in the JSON string but got `%s`", jsonObj.get("courseYear").toString()));
      }
      if ((jsonObj.get("internshipPeriod") != null && !jsonObj.get("internshipPeriod").isJsonNull()) && !jsonObj.get("internshipPeriod").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `internshipPeriod` to be a primitive type in the JSON string but got `%s`", jsonObj.get("internshipPeriod").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Dates.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Dates' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Dates> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Dates.class));

       return (TypeAdapter<T>) new TypeAdapter<Dates>() {
           @Override
           public void write(JsonWriter out, Dates value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Dates read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of Dates given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of Dates
   * @throws IOException if the JSON string is invalid with respect to Dates
   */
  public static Dates fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Dates.class);
  }

  /**
   * Convert an instance of Dates to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

